import type { Metadata } from "next";
import { Nunito_Sans, Montserrat } from "next/font/google";
import Navbar from "./components/shared/Navbar";
import "./globals.css";
import Footer from "./components/shared/Footer";
import { ProductsContext } from "./context/ProductsContext";
import { CartContext } from "./context/CartContext";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} antialiased font-montserrat bg-black`}
      >
        <CartContext>
          <ProductsContext>
            <Navbar />
            <main className="min-h-screen">{children}</main>
            <Footer />
          </ProductsContext>
        </CartContext>
      </body>
    </html>
  );
}
